language: scala
script:
  - sbt clean update compile test package publishOnlyWhenOnMaster
scala:
  - 2.11.0
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
notifications:
  email:
    - eugene.burmako@epfl.ch
    - denys.shabalin@typesafe.com
    - adrien.ghosn@epfl.ch
    - mathieu.demarne@epfl.ch
env:
  global:
   - SCALAREFLECT_MAVEN_REALM="Sonatype Nexus Repository Manager"
   - SCALAREFLECT_MAVEN_DOMAIN="oss.sonatype.org"
   - secure: "Ju5gWK0AG4w7PCeiZuEr37ICPd1AXv/lJPBFtMn9M2V9t9QNucg6C2ZfP3ImxvtLHEG1xzhI/wpihmVz5d5oYjw9mKag33XLbWP6DvBwrI5wfQYZnwFNtFO8gnt4a9IDRu3LSNdTvgGBCfhh4rGJFhdTPuWYkwXNAXBsEIWUZOo="
   - secure: "BdUGPF8o/6z3jvvQ7vALBDuBVQAJwT78SbHeWbYPCTh0eXbxPjRhbIZUpfj30h++e12Fw3oENm0C7umOT0meiPzbp8RPAqAPiqDuGIHvTY3v/gS2HjUQUVyqZWpy3Uu411A4xo7AskwWOhGuc0mr9VkpQBliiCBTMc56O//1YnU="
